/* eslint-disable no-console */
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";

import { initialChats, initialMessages } from "../dummyData";
import ChatSection from "../sections/ChatSection";
import MessageSection from "../sections/MessageSection";
import { chatActions } from "../store/chats-slice";
import { messagesActions } from "../store/messages-slice";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(chatActions.replaceChats(initialChats));
    dispatch(messagesActions.replaceMessages(initialMessages));
  }, []);

  return (
    <div>
      <Head>
        <title>FrontChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="app">
        <ChatSection />
        <MessageSection />
      </div>
    </div>
  );
}
