/* eslint-disable no-console */
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Chats from "../components/Chats";
import Messages from "../components/Messages";

import { initialChats, initialMessages } from "../dummyData";
import { chatActions } from "../store/chats-slice";
import { messagesActions } from "../store/messages-slice";

export default function Home() {
  const allChats = useSelector((state) => state.chats);
  const allMessages = useSelector((state) => state.messages);
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(chatActions.replaceChats(initialChats));
    dispatch(messagesActions.replaceMessages(initialMessages));
  }, []);

  useEffect(() => {
    console.info("look at all chats", allChats);
    console.info("look at all messages", allMessages);
  });

  return (
    <div>
      <Head>
        <title>FrontChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Chats />
      <Messages />
      <h1>Hello from Vitalie Next</h1>
    </div>
  );
}
